

'''VIDEO STABILIZATION CONST.'''
MAX_CORNERS = 500
QUALITY_LEVEL = 0.01
MIN_DISTANCE = 30
BLOCK_SIZE = 3
SMOOTH_RADIUS = 5

'''BACKGROUND SUBSTRACTION CONST.'''
FRAME_INDEX_FOR_PERSON_KDE = 92
NUM_SAMPLES_FOR_KDE = 200
BW_WIDE = 2
BW_MEDIUM = 1
BW_NARROW = 0.3
LEGS_HEIGHT = 805
SHOES_HEIGHT = 870
SHOULDERS_HEIGHT = 405
OVERHEAD_HEIGHT = 160
FRAME_INDEX_FOR_FACE_TUNING = 145
FRAME_INDEX_FOR_SHOES_TUNING = 0

'''MATTING CONST.'''
EPSILON_NARROW_BAND = 0.99
ERODE_ITERATIONS = 6
DILATE_ITERATIONS = 3
GEODISTK_ITERATIONS = 2
REFINEMENT_WINDOW_SIZE = 20
KDE_BW = 1
R = 2
