

'''VIDEO STABILIZATION CONST.'''
MAX_CORNERS = 500
QUALITY_LEVEL = 0.01
MIN_DISTANCE = 30
BLOCK_SIZE = 3
SMOOTH_RADIUS = 5

'''MATTING CONST.'''
EPSILON_NARROW_BAND = 0.99
ERODE_ITERATIONS = 6
DILATE_ITERATIONS = 3
GEODISTK_ITERATIONS = 2
REFINEMENT_WINDOW_SIZE = 20
KDE_BW = 1
R = 2
